# Generated by Django 3.2.9 on 2022-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestcaseDirectory',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='目录名称', max_length=50, verbose_name='目录名称')),
                ('desc', models.TextField(blank=True, help_text='目录描述信息', null=True, verbose_name='目录描述信息')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_directory', to='TestCasesDiretorys.testcasedirectory', verbose_name='父目录')),
                ('projects', models.ForeignKey(db_constraint=False, help_text='项目表外键', on_delete=django.db.models.deletion.CASCADE, related_name='testcase_directory', to='Projects.projects', verbose_name='项目表外键')),
            ],
            options={
                'verbose_name': '用例目录表',
                'verbose_name_plural': '用例目录表',
                'db_table': 'gm_testcases_directory',
                'ordering': ['id'],
            },
        ),
    ]
