# Generated by Django 3.2.9 on 2022-07-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_projects_base_url'),
        ('TestCasesDiretorys', '0002_alter_testcasedirectory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasedirectory',
            name='name',
            field=models.CharField(help_text='目录名称', max_length=50, verbose_name='目录名称'),
        ),
        migrations.AlterField(
            model_name='testcasedirectory',
            name='projects',
            field=models.ForeignKey(db_constraint=False, help_text='项目表外键', on_delete=django.db.models.deletion.CASCADE, related_name='testcase_directory', to='Projects.projects', verbose_name='项目表外键'),
        ),
    ]
