# Generated by Django 3.2.9 on 2022-07-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0004_alter_testcasedirectory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasedirectory',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_directory', to='TestCasesDiretorys.testcasedirectory', verbose_name='父目录'),
        ),
    ]
