# Generated by Django 3.2.9 on 2022-08-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0006_testcasedirectory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasedirectory',
            name='version',
            field=models.IntegerField(default='1.0.1', help_text='版本号', unique=True, verbose_name='版本号'),
        ),
    ]
