# Generated by Django 3.2.9 on 2022-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0011_alter_testcasedirectory_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedirectory',
            name='version',
        ),
    ]
