# Generated by Django 3.2.9 on 2022-08-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0012_remove_testcasedirectory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasedirectory',
            name='desc',
            field=models.TextField(blank=True, help_text='目录描述信息', null=True, verbose_name='目录描述信息'),
        ),
    ]
