# Generated by Django 3.2.9 on 2022-08-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_auto_20220818_2003'),
        ('TestCasesDiretorys', '0013_alter_testcasedirectory_desc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcasedirectory',
            unique_together={('name', 'is_delete', 'projects', 'parent')},
        ),
    ]
