# Generated by Django 3.2.9 on 2022-08-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0014_alter_testcasedirectory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcasedirectory',
            unique_together=set(),
        ),
    ]
