# Generated by Django 3.2.9 on 2022-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestCasesDiretorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('host', models.CharField(blank=True, default='', help_text='接口地址', max_length=100, null=True, verbose_name='接口地址')),
                ('name', models.CharField(help_text='接口名称', max_length=20, verbose_name='接口名称')),
                ('request_type', models.CharField(default='https', help_text='请求类型', max_length=10, verbose_name='请求类型')),
                ('url', models.CharField(help_text='请求url', max_length=100, verbose_name='请求url')),
                ('request_method', models.CharField(default='POST', help_text='请求方式', max_length=10, verbose_name='请求方式')),
                ('request_headers', models.TextField(blank=True, default='', help_text='请求headers', null=True, verbose_name='请求headers')),
                ('body', models.TextField(blank=True, default='', help_text='请求body', null=True, verbose_name='请求body')),
                ('body_type', models.CharField(default='json', help_text='请求body类型', max_length=10, verbose_name='请求body类型')),
                ('assert_list', models.TextField(blank=True, default='', help_text='断言列表', null=True, verbose_name='断言列表')),
                ('out_params', models.TextField(blank=True, default='', help_text='出参列表', null=True, verbose_name='出参列表')),
                ('status', models.CharField(help_text='测试结果', max_length=10, verbose_name='测试结果')),
                ('priority', models.CharField(blank=True, default='', help_text='优先级', max_length=10, null=True, verbose_name='优先级')),
                ('case_type', models.CharField(blank=True, default='', help_text='用例类型', max_length=10, null=True, verbose_name='用例类型')),
                ('response', models.TextField(blank=True, default='', help_text='响应结果', null=True, verbose_name='响应结果')),
                ('developer', models.CharField(blank=True, default='', help_text='开发人员', max_length=10, null=True, verbose_name='开发人员')),
                ('state', models.CharField(blank=True, default='', help_text='状态', max_length=10, null=True, verbose_name='状态')),
                ('tag', models.CharField(blank=True, default='', help_text='标签', max_length=10, null=True, verbose_name='标签')),
                ('desc', models.TextField(blank=True, default='', help_text='接口描述信息', null=True, verbose_name='接口描述信息')),
                ('directory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='TestCasesDiretorys.testcasedirectory', verbose_name='目录表外键')),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'gm_interfaces',
                'ordering': ['id'],
            },
        ),
    ]
