# Generated by Django 3.2.1 on 2022-07-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('TestCasesDiretorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='接口名称', max_length=20, unique=True, verbose_name='接口名称')),
                ('request_type', models.CharField(default='https', help_text='请求类型', max_length=10, verbose_name='请求类型')),
                ('url', models.CharField(help_text='请求url', max_length=100, unique=True, verbose_name='请求url')),
                ('request_method', models.CharField(help_text='请求方式', max_length=10, unique=True, verbose_name='请求方式')),
                ('request_headers', models.TextField(blank=True, default='', help_text='请求headers', null=True, verbose_name='请求headers')),
                ('body', models.TextField(blank=True, default='', help_text='请求body', null=True, verbose_name='请求body')),
                ('body_type', models.CharField(help_text='请求body类型', max_length=10, unique=True, verbose_name='请求body类型')),
                ('expected_result', models.TextField(blank=True, default='', help_text='预期结果', null=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, default='', help_text='实际结果', null=True, verbose_name='实际结果')),
                ('status', models.CharField(help_text='测试结果', max_length=10, verbose_name='测试结果')),
                ('priority', models.IntegerField(help_text='优先级', verbose_name='优先级')),
                ('case_type', models.CharField(help_text='用例类型', max_length=10, verbose_name='用例类型')),
                ('tag', models.CharField(help_text='标签', max_length=10, verbose_name='标签')),
                ('directory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='TestCasesDiretorys.testcasedirectory', verbose_name='目录表外键')),
                ('projects', models.ForeignKey(db_constraint=False, help_text='项目表外键', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='Projects.projects', verbose_name='项目表外键')),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'gm_interfaces',
                'ordering': ['id'],
            },
        ),
    ]
