# Generated by Django 3.2.9 on 2022-12-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='project',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='Projects.projects', verbose_name='项目表外键'),
            preserve_default=False,
        ),
    ]
