# Generated by Django 3.2.9 on 2022-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0002_interfaces_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='developer',
            field=models.CharField(default='宋文', help_text='开发人员', max_length=10, verbose_name='开发人员'),
            preserve_default=False,
        ),
    ]
