# Generated by Django 3.2.9 on 2022-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0002_interfaces_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=50, verbose_name='接口名称'),
        ),
    ]
