# Generated by Django 3.2.9 on 2022-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0006_alter_interfaces_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='version',
            field=models.CharField(help_text='版本号', max_length=50, verbose_name='版本号'),
        ),
    ]
