# Generated by Django 3.2.9 on 2022-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0008_alter_interfaces_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='version',
        ),
    ]
