# Generated by Django 3.2.9 on 2022-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0009_remove_interfaces_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='projects',
        ),
        migrations.AddField(
            model_name='interfaces',
            name='state',
            field=models.CharField(default='1', help_text='状态', max_length=10, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
