# Generated by Django 3.2.9 on 2022-08-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCasesDiretorys', '0012_remove_testcasedirectory_version'),
        ('Interfaces', '0010_auto_20220817_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='接口描述信息', null=True, verbose_name='接口描述信息'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='directory',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='TestCasesDiretorys.testcasedirectory', verbose_name='目录表外键'),
        ),
    ]
