# Generated by Django 3.2.9 on 2022-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0011_auto_20220817_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='body_type',
            field=models.CharField(default='json', help_text='请求body类型', max_length=10, verbose_name='请求body类型'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='request_method',
            field=models.CharField(default='POST', help_text='请求方式', max_length=10, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='url',
            field=models.CharField(help_text='请求url', max_length=100, verbose_name='请求url'),
        ),
    ]
