# Generated by Django 3.2.9 on 2022-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0012_auto_20220818_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interfaces',
            unique_together={('name', 'is_delete')},
        ),
    ]
