# Generated by Django 3.2.9 on 2022-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0013_alter_interfaces_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=20, verbose_name='接口名称'),
        ),
    ]
