# Generated by Django 3.2.9 on 2022-08-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0014_alter_interfaces_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interfaces',
            unique_together=set(),
        ),
    ]
