# Generated by Django 3.2.9 on 2022-09-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0015_alter_interfaces_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='host',
            field=models.CharField(blank=True, default='', help_text='接口地址', max_length=100, null=True, verbose_name='接口地址'),
        ),
    ]
