# Generated by Django 3.2.9 on 2022-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0016_interfaces_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='expected_result',
        ),
        migrations.AddField(
            model_name='interfaces',
            name='assert_list',
            field=models.TextField(blank=True, default='', help_text='断言列表', null=True, verbose_name='断言列表'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='developer',
            field=models.CharField(blank=True, default='', help_text='开发人员', max_length=10, null=True, verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='priority',
            field=models.CharField(blank=True, default='', help_text='优先级', max_length=10, null=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='state',
            field=models.CharField(blank=True, default='', help_text='状态', max_length=10, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='标签', max_length=10, null=True, verbose_name='标签'),
        ),
    ]
