# Generated by Django 3.2.9 on 2022-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0017_auto_20220906_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='case_type',
            field=models.CharField(blank=True, default='', help_text='用例类型', max_length=10, null=True, verbose_name='用例类型'),
        ),
    ]
