# Generated by Django 3.2.9 on 2022-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0018_alter_interfaces_case_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='actual_result',
        ),
        migrations.AddField(
            model_name='interfaces',
            name='out_params',
            field=models.TextField(blank=True, default='', help_text='出参列表', null=True, verbose_name='出参列表'),
        ),
    ]
