# Generated by Django 3.2.9 on 2022-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0019_auto_20220908_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='response',
            field=models.TextField(blank=True, default='', help_text='响应结果', null=True, verbose_name='响应结果'),
        ),
    ]
