# Generated by Django 3.2.9 on 2022-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('base_url', models.CharField(blank=True, help_text='项目基础url', max_length=50, null=True, verbose_name='项目基础url')),
                ('owner', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('app', models.CharField(help_text='项目所属应用', max_length=50, verbose_name='项目所属应用')),
                ('type', models.CharField(help_text='项目类型', max_length=50, verbose_name='项目类型')),
                ('desc', models.TextField(blank=True, default='', help_text='项目描述信息', null=True, verbose_name='项目描述信息')),
                ('version', models.CharField(help_text='版本号', max_length=50, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'gm_projects',
                'ordering': ['id'],
            },
        ),
    ]
