# Generated by Django 3.2.9 on 2022-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='base_url',
            field=models.CharField(blank=True, help_text='项目基础url', max_length=50, null=True, verbose_name='项目基础url'),
        ),
    ]
