# Generated by Django 3.2.9 on 2022-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_projects_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='version',
            field=models.IntegerField(default=1.0, help_text='版本号', unique=True, verbose_name='版本号'),
        ),
    ]
