# Generated by Django 3.2.9 on 2022-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projects_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(default='web', help_text='项目类型', max_length=50, unique=True, verbose_name='项目类型'),
            preserve_default=False,
        ),
    ]
