# Generated by Django 3.2.9 on 2022-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_projects_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='version',
            field=models.CharField(default='1.0.1', help_text='版本号', max_length=50, unique=True, verbose_name='版本号'),
        ),
    ]
