# Generated by Django 3.2.9 on 2022-08-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_projects_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(help_text='项目类型', max_length=50, verbose_name='项目类型'),
        ),
    ]
