# Generated by Django 3.2.9 on 2022-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_alter_projects_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='version',
            field=models.CharField(help_text='版本号', max_length=50, verbose_name='版本号'),
        ),
    ]
