# Generated by Django 3.2.9 on 2022-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_alter_projects_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('name', 'is_delete')},
        ),
    ]
