# Generated by Django 3.2.9 on 2022-08-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_auto_20220818_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together=set(),
        ),
    ]
