# Generated by Django 3.2.9 on 2022-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('Interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='套件名称', max_length=200, verbose_name='套件名称')),
                ('cron', models.CharField(blank=True, help_text='定时任务', max_length=100, null=True, verbose_name='定时任务')),
                ('priority', models.CharField(blank=True, default='P0', help_text='优先级', max_length=50, null=True, verbose_name='优先级')),
                ('status', models.TextField(blank=True, default='', help_text='执行结果', null=True, verbose_name='执行结果')),
                ('success_count', models.CharField(blank=True, help_text='成功用例数', max_length=50, null=True, verbose_name='成功用例数')),
                ('failure_count', models.CharField(blank=True, help_text='失败用例数', max_length=50, null=True, verbose_name='失败用例数')),
                ('error_count', models.CharField(blank=True, help_text='错误用例数', max_length=50, null=True, verbose_name='错误用例数')),
                ('skip_count', models.CharField(blank=True, help_text='跳过用例数', max_length=50, null=True, verbose_name='跳过用例数')),
                ('total_count', models.CharField(blank=True, help_text='总用例数', max_length=50, null=True, verbose_name='总用例数')),
                ('report_name', models.TextField(blank=True, help_text='报告名', max_length=1000, null=True, verbose_name='报告名')),
                ('state', models.CharField(blank=True, default='未完成', help_text='状态', max_length=50, null=True, verbose_name='状态')),
                ('desc', models.TextField(blank=True, default='', help_text='简要描述', null=True, verbose_name='简要描述')),
                ('case_list', models.ManyToManyField(db_constraint=False, help_text='用例列表', related_name='testsuit_interfaces', to='Interfaces.Interfaces')),
                ('project', models.ForeignKey(db_constraint=False, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='testsuit_project', to='Projects.projects')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'gm_testsuits',
                'ordering': ['id'],
            },
        ),
    ]
