# Generated by Django 3.2.9 on 2022-09-23 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuit',
            name='create_user',
            field=models.CharField(default='test', help_text='创建人', max_length=50, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuit',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuit',
            name='deleted_time',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='update_user',
            field=models.CharField(default='test', help_text='更新人', max_length=50, verbose_name='更新人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuit',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='id',
            field=models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id'),
        ),
    ]
