# Generated by Django 3.2.9 on 2022-12-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaces', '0001_initial'),
        ('TestSuit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuit',
            name='case_list',
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='status',
            field=models.TextField(blank=True, help_text='执行结果', null=True, verbose_name='执行结果'),
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('execution_order', models.IntegerField(default=1, help_text='执行顺序', verbose_name='执行顺序')),
                ('status', models.TextField(blank=True, help_text='执行结果', null=True, verbose_name='执行结果')),
                ('desc', models.TextField(blank=True, default='', help_text='简要描述', null=True, verbose_name='简要描述')),
                ('interface', models.ForeignKey(db_constraint=False, help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, related_name='interface_step', to='Interfaces.interfaces')),
                ('testsuit', models.ForeignKey(db_constraint=False, help_text='所属套件', on_delete=django.db.models.deletion.CASCADE, related_name='testsuit_step', to='TestSuit.testsuit')),
            ],
            options={
                'verbose_name': '测试用例步骤',
                'verbose_name_plural': '测试用例步骤',
                'db_table': 'gm_testcase_step',
                'ordering': ['id'],
            },
        ),
    ]
