# Generated by Django 3.2.9 on 2022-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='status',
            field=models.CharField(blank=True, help_text='执行结果', max_length=500, null=True, verbose_name='执行结果'),
        ),
    ]
