# Generated by Django 3.2.9 on 2022-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='execution_order',
            field=models.IntegerField(blank=True, help_text='执行顺序', max_length=20, null=True, verbose_name='执行顺序'),
        ),
    ]
