# Generated by Django 3.2.9 on 2022-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuit',
            name='error_count',
            field=models.CharField(blank=True, help_text='错误用例数', max_length=50, null=True, verbose_name='错误用例数'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='failure_count',
            field=models.CharField(blank=True, help_text='失败用例数', max_length=50, null=True, verbose_name='失败用例数'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='report_source_code',
            field=models.CharField(blank=True, help_text='报告源码', max_length=1000, null=True, verbose_name='报告源码'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='skip_count',
            field=models.CharField(blank=True, help_text='跳过用例数', max_length=50, null=True, verbose_name='跳过用例数'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='status',
            field=models.CharField(blank=True, help_text='执行结果', max_length=50, null=True, verbose_name='执行结果'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='success_count',
            field=models.CharField(blank=True, help_text='成功用例数', max_length=50, null=True, verbose_name='成功用例数'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='total_count',
            field=models.CharField(blank=True, help_text='总用例数', max_length=50, null=True, verbose_name='总用例数'),
        ),
    ]
