# Generated by Django 3.2.9 on 2022-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0002_auto_20221008_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='report_source_code',
            field=models.TextField(blank=True, help_text='报告源码', max_length=1000, null=True, verbose_name='报告源码'),
        ),
    ]
