# Generated by Django 3.2.9 on 2022-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0002_auto_20220923_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='name',
            field=models.CharField(help_text='套件名称', max_length=200, verbose_name='套件名称'),
        ),
    ]
