# Generated by Django 3.2.9 on 2022-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0002_alter_testsuit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='status',
            field=models.TextField(blank=True, help_text='执行结果', null=True, verbose_name='执行结果'),
        ),
    ]
