# Generated by Django 3.2.9 on 2022-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0003_alter_testcasestep_execution_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuit',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='failure_count',
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='report_name',
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='skip_count',
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='success_count',
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='total_count',
        ),
        migrations.AddField(
            model_name='testsuit',
            name='run_duration',
            field=models.CharField(blank=True, help_text='运行时长', max_length=50, null=True, verbose_name='运行时长'),
        ),
    ]
