# Generated by Django 3.2.9 on 2022-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0003_alter_testsuit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='priority',
            field=models.CharField(blank=True, default='P0', help_text='优先级', max_length=50, null=True, verbose_name='优先级'),
        ),
    ]
