# Generated by Django 3.2.9 on 2022-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0003_alter_testsuit_report_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='status',
            field=models.CharField(blank=True, help_text='执行结果', max_length=500, null=True, verbose_name='执行结果'),
        ),
    ]
