# Generated by Django 3.2.9 on 2022-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0004_auto_20221207_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='run_duration',
            field=models.FloatField(blank=True, default=0, help_text='运行时长', null=True, verbose_name='运行时长'),
        ),
    ]
