# Generated by Django 3.2.9 on 2022-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0004_alter_testsuit_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='state',
            field=models.CharField(blank=True, default='未执行', help_text='状态', max_length=50, null=True, verbose_name='状态'),
        ),
    ]
