# Generated by Django 3.2.9 on 2022-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0005_alter_testsuit_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='简要描述', null=True, verbose_name='简要描述'),
        ),
    ]
