# Generated by Django 3.2.9 on 2022-09-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configs', '0002_alter_config_unique_together'),
        ('Projects', '0013_alter_projects_unique_together'),
        ('Interfaces', '0019_auto_20220908_1104'),
        ('TestSuit', '0005_alter_testsuit_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuit',
            options={'ordering': ['id'], 'verbose_name': '测试套件', 'verbose_name_plural': '测试套件'},
        ),
        migrations.RemoveField(
            model_name='testsuit',
            name='case_list',
        ),
        migrations.AddField(
            model_name='testsuit',
            name='case_list',
            field=models.ManyToManyField(db_constraint=False, help_text='用例列表', related_name='testsuit_interfaces', to='Interfaces.Interfaces'),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='env',
            field=models.ForeignKey(db_constraint=False, help_text='所属环境', on_delete=django.db.models.deletion.CASCADE, related_name='testsuit_env', to='Configs.config'),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='testsuit_project', to='Projects.projects'),
        ),
    ]
