# Generated by Django 3.2.9 on 2022-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0006_alter_testsuit_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuit',
            name='report_source_code',
        ),
        migrations.AddField(
            model_name='testsuit',
            name='report_name',
            field=models.TextField(blank=True, help_text='报告名', max_length=1000, null=True, verbose_name='报告名'),
        ),
    ]
