# Generated by Django 3.2.9 on 2022-09-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestSuit', '0006_auto_20220924_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuit',
            name='env',
        ),
    ]
