# Generated by Django 3.2.9 on 2022-08-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
    ]
