# Generated by Django 3.2.9 on 2022-12-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('TestSuit', '0004_auto_20221207_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('update_user', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('deleted_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='报告名称', max_length=50, verbose_name='报告名称')),
                ('success_count', models.CharField(blank=True, help_text='成功用例数', max_length=50, null=True, verbose_name='成功用例数')),
                ('failure_count', models.CharField(blank=True, help_text='失败用例数', max_length=50, null=True, verbose_name='失败用例数')),
                ('error_count', models.CharField(blank=True, help_text='错误用例数', max_length=50, null=True, verbose_name='错误用例数')),
                ('skip_count', models.CharField(blank=True, help_text='跳过用例数', max_length=50, null=True, verbose_name='跳过用例数')),
                ('total_count', models.CharField(blank=True, help_text='总用例数', max_length=50, null=True, verbose_name='总用例数')),
                ('report_name', models.TextField(blank=True, help_text='报告名', max_length=1000, null=True, verbose_name='报告名')),
                ('status', models.CharField(blank=True, help_text='状态', max_length=50, null=True, verbose_name='状态')),
                ('state', models.CharField(blank=True, help_text='状态', max_length=50, null=True, verbose_name='状态')),
                ('project', models.ForeignKey(blank=True, help_text='项目id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects', verbose_name='项目id')),
                ('testsuit', models.ForeignKey(blank=True, help_text='测试套件id', null=True, on_delete=django.db.models.deletion.CASCADE, to='TestSuit.testsuit', verbose_name='测试套件id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
