# Generated by Django 3.2.9 on 2022-12-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': '报告', 'verbose_name_plural': '报告'},
        ),
        migrations.AlterModelTable(
            name='reports',
            table='gm_reports',
        ),
    ]
