# Generated by Django 3.2.9 on 2022-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20221207_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.TextField(blank=True, help_text='状态', null=True, verbose_name='状态'),
        ),
    ]
